package br.ufsc.ui;

import br.ufsc.constant.Autoridade;

public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bCriarNovaTurma = new javax.swing.JButton();
        bCriarNovoProfessor = new javax.swing.JButton();
        dadosAdmin = new javax.swing.JLabel();
        bListarTurmasProfessor = new javax.swing.JButton();
        bNovoAdministrador = new javax.swing.JButton();
        bChangeUser = new javax.swing.JButton();
        bSairSistema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visão do Administrador");
        setResizable(false);

        jLabel1.setText("Administrador (a)");

        bCriarNovaTurma.setText("Criar Nova Turma");
        bCriarNovaTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCriarNovaTurmaActionPerformed(evt);
            }
        });

        bCriarNovoProfessor.setText("Criar Novo (a) Professor (a)");
        bCriarNovoProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCriarNovoProfessorActionPerformed(evt);
            }
        });

        dadosAdmin.setText("Nome (CPF)");

        bListarTurmasProfessor.setText("Listar as turmas de um professor");
        bListarTurmasProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarTurmasProfessorActionPerformed(evt);
            }
        });

        bNovoAdministrador.setText("Novo (a) Administrador (a)");
        bNovoAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNovoAdministradorActionPerformed(evt);
            }
        });

        bChangeUser.setText("Entrar com outro usuário");
        bChangeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChangeUserActionPerformed(evt);
            }
        });

        bSairSistema.setText("Sair");
        bSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dadosAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bCriarNovaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(bNovoAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bCriarNovoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bListarTurmasProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bChangeUser, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(bSairSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCriarNovaTurma)
                    .addComponent(bNovoAdministrador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCriarNovoProfessor)
                    .addComponent(bChangeUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bListarTurmasProfessor)
                    .addComponent(bSairSistema))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dadosAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCriarNovoProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCriarNovoProfessorActionPerformed
        ProfessorForm pf = new ProfessorForm();
        pf.launch();
    }//GEN-LAST:event_bCriarNovoProfessorActionPerformed

    private void bCriarNovaTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCriarNovaTurmaActionPerformed
        TurmaForm tf = new TurmaForm();
        tf.launch();
    }//GEN-LAST:event_bCriarNovaTurmaActionPerformed

    private void bListarTurmasProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarTurmasProfessorActionPerformed
        ListaTurmasProfessor ltp = new ListaTurmasProfessor();
        ltp.launch(cpf, Autoridade.ADMIN);
    }//GEN-LAST:event_bListarTurmasProfessorActionPerformed

    private void bNovoAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNovoAdministradorActionPerformed
        // TODO add your handling code here:
        AdministradorForm af = new AdministradorForm();
        af.launch();
    }//GEN-LAST:event_bNovoAdministradorActionPerformed

    private void bChangeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChangeUserActionPerformed
        Login l = new Login();
        l.launch();
    }//GEN-LAST:event_bChangeUserActionPerformed

    private void bSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSairSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void launch() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bChangeUser;
    private javax.swing.JButton bCriarNovaTurma;
    private javax.swing.JButton bCriarNovoProfessor;
    private javax.swing.JButton bListarTurmasProfessor;
    private javax.swing.JButton bNovoAdministrador;
    private javax.swing.JButton bSairSistema;
    private javax.swing.JLabel dadosAdmin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private String nome;
    private String cpf;

    void setDadosAdmin(String nome, String cpf) {
        this.nome = nome;
        this.cpf = cpf;
        dadosAdmin.setText(nome + " (" + cpf + ").");
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
}
