package br.ufsc.ui;

import br.ufsc.control.EstudanteController;
import java.util.*;
import javax.swing.table.*;
import javax.swing.*;

public class Estudante extends javax.swing.JFrame {

    /**
     * Creates new form Estudante
     */
    public Estudante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bListarCursosFeitos = new javax.swing.JButton();
        bListarCursosAndamento = new javax.swing.JButton();
        dadosEstudante = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCursosFinalizados = new JTable(new DefaultTableModel());
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bMatricular = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaCursosEmAndamento = new JTable(new DefaultTableModel());
        bChangeUser = new javax.swing.JButton();
        bSairSistema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visão do Estudante");
        setResizable(false);

        jLabel1.setText("Estudante");

        bListarCursosFeitos.setText("Listar Cursos Feitos");
        bListarCursosFeitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarCursosFeitosActionPerformed(evt);
            }
        });

        bListarCursosAndamento.setText("Listar Cursos em Andamento");
        bListarCursosAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarCursosAndamentoActionPerformed(evt);
            }
        });

        dadosEstudante.setText("Nome (CPF)");

        tabelaCursosFinalizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Idioma", "Nível", "Estado", "Avaliação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCursosFinalizados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaCursosFinalizados);

        jLabel2.setText("Cursos Feitos");

        jLabel3.setText("Cursos em Andamento");

        bMatricular.setText("Matricular");
        bMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMatricularActionPerformed(evt);
            }
        });

        tabelaCursosEmAndamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Turma", "Idioma", "Nivel", "Bloco Horário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCursosEmAndamento.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabelaCursosEmAndamento);

        bChangeUser.setText("Entrar com outro usuário");
        bChangeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChangeUserActionPerformed(evt);
            }
        });

        bSairSistema.setText("Sair");
        bSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(dadosEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 461, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(bListarCursosFeitos, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bChangeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(bListarCursosAndamento, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bSairSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(bMatricular, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bListarCursosFeitos)
                    .addComponent(bMatricular)
                    .addComponent(bChangeUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bListarCursosAndamento)
                    .addComponent(bSairSistema))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dadosEstudante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bListarCursosFeitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarCursosFeitosActionPerformed
        // TODO add your handling code here:
        EstudanteController ec = new EstudanteController();
        ArrayList<String[]> finalizados = ec.getCursosFinalizados(cpf);
        getTabelaCursosFinalizados().getDataVector().removeAllElements();
        getTabelaCursosFinalizados().fireTableDataChanged();
        for (String[] curso : finalizados) {
            setRowTabelaCursosFinalizados(curso);
        }
        ec = null;
    }//GEN-LAST:event_bListarCursosFeitosActionPerformed

    public void setRowTabelaCursosFinalizados(Object[] data) {
        getTabelaCursosFinalizados().addRow(data);
    }

    public void setRowTabelaCursosEmAndamento(Object[] data) {
        getTabelaCursosEmAndamento().addRow(data);
    }

    public DefaultTableModel getTabelaCursosFinalizados() {
        return (DefaultTableModel) tabelaCursosFinalizados.getModel();
    }

    public DefaultTableModel getTabelaCursosEmAndamento() {
        return (DefaultTableModel) tabelaCursosEmAndamento.getModel();
    }

    private void bMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMatricularActionPerformed
        // TODO add your handling code here:
        MatriculaForm mf = new MatriculaForm();
        mf.launch(cpf);
    }//GEN-LAST:event_bMatricularActionPerformed

    private void bListarCursosAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarCursosAndamentoActionPerformed
        // TODO add your handling code here:
        EstudanteController ec = new EstudanteController();
        ArrayList<String[]> andamento = ec.getCursosEmAndamento(cpf);
        getTabelaCursosEmAndamento().getDataVector().removeAllElements();
        getTabelaCursosEmAndamento().fireTableDataChanged();
        for (String[] curso : andamento) {
            setRowTabelaCursosEmAndamento(curso);
        }
        ec = null;
    }//GEN-LAST:event_bListarCursosAndamentoActionPerformed

    private void bChangeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChangeUserActionPerformed
        Login l = new Login();
        l.launch();
    }//GEN-LAST:event_bChangeUserActionPerformed

    private void bSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSairSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void launch() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estudante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bChangeUser;
    private javax.swing.JButton bListarCursosAndamento;
    private javax.swing.JButton bListarCursosFeitos;
    private javax.swing.JButton bMatricular;
    private javax.swing.JButton bSairSistema;
    private javax.swing.JLabel dadosEstudante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelaCursosEmAndamento;
    private javax.swing.JTable tabelaCursosFinalizados;
    // End of variables declaration//GEN-END:variables
    private String nome;
    private String cpf;

    public void setDadosEstudante(String nome, String cpf) {
        this.nome = nome;
        this.cpf = cpf;
        dadosEstudante.setText(nome + " (" + cpf + ").");
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
}
