package br.ufsc.ui;

import br.ufsc.constant.*;
import br.ufsc.control.*;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bLoginAuth = new javax.swing.JButton();
        bSairSistema = new javax.swing.JButton();
        tfLoginCpf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfLoginSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        bFormNovaPessoa = new javax.swing.JButton();
        bInfo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Entrada no Sistema");
        setResizable(false);

        bLoginAuth.setText("Autenticar");
        bLoginAuth.setMaximumSize(new java.awt.Dimension(150, 40));
        bLoginAuth.setMinimumSize(new java.awt.Dimension(150, 40));
        bLoginAuth.setPreferredSize(new java.awt.Dimension(150, 40));
        bLoginAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginAuthActionPerformed(evt);
            }
        });

        bSairSistema.setText("Sair");
        bSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairSistemaActionPerformed(evt);
            }
        });

        tfLoginCpf.setMaximumSize(new java.awt.Dimension(140, 40));
        tfLoginCpf.setMinimumSize(new java.awt.Dimension(140, 40));

        jLabel1.setText("Insira seu cpf");

        jLabel2.setText("Insira sua senha");

        tfLoginSenha.setMaximumSize(new java.awt.Dimension(140, 40));
        tfLoginSenha.setMinimumSize(new java.awt.Dimension(140, 40));

        jLabel4.setText("Para cadastro de professores entrar em contato com um administrador.");

        bFormNovaPessoa.setText("Novo Estudante");
        bFormNovaPessoa.setMaximumSize(new java.awt.Dimension(150, 40));
        bFormNovaPessoa.setMinimumSize(new java.awt.Dimension(150, 40));
        bFormNovaPessoa.setPreferredSize(new java.awt.Dimension(150, 40));
        bFormNovaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFormNovaPessoaActionPerformed(evt);
            }
        });

        bInfo.setText("Info");
        bInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInfoActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSairSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bInfo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 183, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bLoginAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bFormNovaPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfLoginSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfLoginCpf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLoginCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLoginSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bLoginAuth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFormNovaPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSairSistema)
                    .addComponent(bInfo))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginAuthActionPerformed
        executeLogin();
    }//GEN-LAST:event_bLoginAuthActionPerformed

    private void bSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSairSistemaActionPerformed

    private void bFormNovaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFormNovaPessoaActionPerformed
        // TODO add your handling code here:
        PessoaForm pf = new PessoaForm();
        pf.launch();
    }//GEN-LAST:event_bFormNovaPessoaActionPerformed

    private void bInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInfoActionPerformed
        info();
    }//GEN-LAST:event_bInfoActionPerformed

    public void executeLogin() {
        String cpf = tfLoginCpf.getText();
        char[] senha = tfLoginSenha.getPassword();
        Mensagem m = new Mensagem();

        if (cpf.length() == 0 || senha.length == 0) {
            m.setMensagemSistema(String.format("Problemas de autorização. Revise CPF e Senha.\n"));
            m.launch();
        } else {
            AuthController ac = new AuthController();
            Autoridade autoridade = ac.check(cpf, senha);
            if (autoridade.equals(Autoridade.ESTUDANTE)) {
                Estudante estudanteView = new Estudante();
                String nome = new EstudanteController().getNome(cpf);

                System.out.println(nome);

                estudanteView.setDadosEstudante(nome, cpf);
                estudanteView.launch();

                m.launch();
                m.setMensagemSistema("Estudante entrou no sistema.\n");

                this.dispose();
            } else if (autoridade.equals(Autoridade.PROFESSOR)) {
                Professor professorView = new Professor();
                ProfessorController pc = new ProfessorController();
                String nome = pc.getNome(cpf);
                professorView.setDadosProfessor(nome, cpf);
                professorView.launch();

                System.out.println(nome);

                m.launch();
                m.setMensagemSistema("Professor entrou no sistema.\n");

                this.dispose();
            } else if (autoridade.equals(Autoridade.ADMIN)) {
                Administrador adminView = new Administrador();
                String nome = new AdministradorController().getNome(cpf);
                adminView.setDadosAdmin(nome, cpf);
                adminView.launch();

                System.out.println(nome);

                m.launch();
                m.setMensagemSistema("Administrador entrou no sistema.\n");

                this.dispose();
            } else {
                m.launch();
                m.setMensagemSistema("Nenhum perfil encontrado para os dados fornecidos.\n"
                        + "(soluções: Crie Um Cadastro,\n"
                        + "Verifique se o CPF e SENHA estão corretos).\n");
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public void launch() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });

    }

    public void info() {
        new Mensagem("Trabalho 1\n"
                + "INE5612-04238A (20191) - Desenvolvimento de Sistemas Orientados a Objetos II\n"
                + "Professor: Alex Sandro Roschildt Pinto.\n"
                + "Grupo:\n"
                + "\t1. Amanda Martins Haase (926966).\n"
                + "\t2. Lucas Pagotto Tonussi (18250265).\n"
                + "Criar uma banco de dados mysql com o nome masteridiomas.\n"
                + "Execute no seu mysql: CREATE DATABASE masteridiomas;\n"
                + "Criar um usuário mysql chamado masteridiomas e com senha masteridiomas.\n"
                + "Execute no seu mysql: CREATE USER masteridiomas IDENTIFIED BY 'masteridiomas';\n"
                + "Execute no seu mysql: GRANT ALL PRIVILEGES ON public.masteridiomas TO masteridiomas;\n"
                + "As vezes será preciso executar no seu mysql:"
                + "GRANT CREATE, DELETE, UPDATE, ALTER, REFEREMCES, INDEX on public.masteridiomas TO masteridiomas;\n"
                + "Esse projeto foi feito sob '/usr/lib/jvm/java-8-oracle' Java SE JDK 1.8.\n"
                + "Para instalar no Ubuntu: 'sudo apt install oracle-java8-installer'\n"
                + "Interface gráfica: Java Swing.\n"
                + "Login de um ADMIN:\n"
                + "\tCPF: 085\n"
                + "\tSENHA: admin\n"
                + "Login de um PROFESSOR:\n"
                + "\tCPF: 093\n"
                + "\tSENHA: rute\n"
                + "Login de um ESTUDANTE:\n"
                + "\tCPF: 012\n"
                + "\tSENHA: debora\n").launch();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFormNovaPessoa;
    private javax.swing.JButton bInfo;
    private javax.swing.JButton bLoginAuth;
    private javax.swing.JButton bSairSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField tfLoginCpf;
    private javax.swing.JPasswordField tfLoginSenha;
    // End of variables declaration//GEN-END:variables
}
