package br.ufsc.ui;

import br.ufsc.control.*;
import java.util.*;
import javax.swing.table.*;
import javax.swing.*;

public class MatriculaForm extends javax.swing.JFrame {

    /**
     * Creates new form MatriculaForm
     */
    public MatriculaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bMatricular = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaTurmas = new JTable(new DefaultTableModel());
        bBuscarTurmasExistentes = new javax.swing.JButton();
        bSairMatriculaForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova Matrícula");
        setResizable(false);

        jLabel1.setText("Disciplinas Disponíveis (Compatíveis), Selecione a turma do seu interece.");

        bMatricular.setText("Me Matricular Nesta Turma");
        bMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMatricularActionPerformed(evt);
            }
        });

        tabelaTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Turma", "Bloco Horários", "Idioma", "Nível", "Professor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaTurmas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaTurmas);

        bBuscarTurmasExistentes.setText("Buscar Turmas Disponíveis");
        bBuscarTurmasExistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarTurmasExistentesActionPerformed(evt);
            }
        });

        bSairMatriculaForm.setText("Sair");
        bSairMatriculaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairMatriculaFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 477, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bBuscarTurmasExistentes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bMatricular))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bSairMatriculaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBuscarTurmasExistentes)
                    .addComponent(bMatricular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSairMatriculaForm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMatricularActionPerformed
        // TODO add your handling code here:
        MatriculaController mc = new MatriculaController();
        int row = tabelaTurmas.getSelectedRow();
        if (row > -1) {
            tabelaTurmas.setRowSelectionInterval(row, row);
            Integer idTurma = Integer.valueOf(getTabelaTurmas().getValueAt(row, 0).toString());
            boolean check = mc.adicionarMatricula(cpfEstudante, idTurma);
            if (!check) {
                new Mensagem("Possíveis Erros:\n"
                        + "1. Você já está matriculado em uma turma para esse idioma e nível.\n"
                        + "2. Ou você não tem nível suficiente para entrar nessa turma.\n"
                        + "3. Ou você já foi aprovado nessa turma para esse idioma e nível.\n").launch();
            }
        }
        mc = null;
    }//GEN-LAST:event_bMatricularActionPerformed

    private void bBuscarTurmasExistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarTurmasExistentesActionPerformed
        // TODO add your handling code here:
        TurmaController tc = new TurmaController();
        ArrayList<String[]> turmasEspecificasEstudante = tc.getTurmasParaUmEstudanteSeMatricular(cpfEstudante);
        getTabelaTurmas().getDataVector().removeAllElements();
        getTabelaTurmas().fireTableDataChanged();
        for (String[] turma : turmasEspecificasEstudante) {
            setRowAtTabelaTurmas(turma);
        }
        tc = null;
    }//GEN-LAST:event_bBuscarTurmasExistentesActionPerformed

    private void bSairMatriculaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairMatriculaFormActionPerformed
        dispose();
    }//GEN-LAST:event_bSairMatriculaFormActionPerformed

    private DefaultTableModel getTabelaTurmas() {
        return (DefaultTableModel) tabelaTurmas.getModel();
    }

    private void setRowAtTabelaTurmas(Object[] turma) {
        getTabelaTurmas().addRow(turma);
    }

    /**
     * @param args the command line arguments
     */
    public void launch(String cpf) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatriculaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        setCpf(cpf);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscarTurmasExistentes;
    private javax.swing.JButton bMatricular;
    private javax.swing.JButton bSairMatriculaForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaTurmas;
    // End of variables declaration//GEN-END:variables
    private String cpfEstudante;

    public String getCpf() {
        return cpfEstudante;
    }

    public void setCpf(String cpf) {
        this.cpfEstudante = cpf;
    }
}
