package br.ufsc.ui;

import br.ufsc.constant.Autoridade;
import br.ufsc.control.ProfessorController;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

public class Professor extends javax.swing.JFrame {

    /**
     * Creates new form Professor
     */
    public Professor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dadosProfessor = new javax.swing.JLabel();
        bListarTurmas = new javax.swing.JButton();
        bAvaliarTurma = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaTurmasProfessor = new JTable(new DefaultTableModel());
        jLabel2 = new javax.swing.JLabel();
        bListarMinhasTurmasComEstudantes = new javax.swing.JButton();
        bChangeUser = new javax.swing.JButton();
        bSairSistema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visão do Professor");
        setResizable(false);

        jLabel1.setText("Professor (a)");

        dadosProfessor.setText("Nome (CPF)");

        bListarTurmas.setText("Listar Minhas Turmas");
        bListarTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarTurmasActionPerformed(evt);
            }
        });

        bAvaliarTurma.setText("Avaliar");
        bAvaliarTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAvaliarTurmaActionPerformed(evt);
            }
        });

        tabelaTurmasProfessor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Turma", "Blocos de Horários", "Idioma", "Nível", "Professor (a)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaTurmasProfessor.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaTurmasProfessor);

        jLabel2.setText("Selecione uma turma para avaliar os estudantes, ou fechar a turma.");

        bListarMinhasTurmasComEstudantes.setText("Listar Minhas Turmas e Meus Alunos (as)");
        bListarMinhasTurmasComEstudantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarMinhasTurmasComEstudantesActionPerformed(evt);
            }
        });

        bChangeUser.setText("Entrar com outro usuário");
        bChangeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChangeUserActionPerformed(evt);
            }
        });

        bSairSistema.setText("Sair");
        bSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bListarTurmas)
                                .addGap(240, 240, 240)
                                .addComponent(bAvaliarTurma))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bListarMinhasTurmasComEstudantes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bChangeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 273, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(dadosProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bSairSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bListarMinhasTurmasComEstudantes)
                            .addComponent(bChangeUser))
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bListarTurmas)
                            .addComponent(bAvaliarTurma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(dadosProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bSairSistema)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bListarTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarTurmasActionPerformed
        ProfessorController pc = new ProfessorController();
        ArrayList<String[]> turmas = pc.getTurmasProfessorByCpf(cpf);
        getTabelaTurmasProfessor().getDataVector().removeAllElements();
        getTabelaTurmasProfessor().fireTableDataChanged();
        for (Object[] turma : turmas) {
            setRowTabelaTurmasProfessor(turma);
        }
        pc = null;
    }//GEN-LAST:event_bListarTurmasActionPerformed

    private void bAvaliarTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAvaliarTurmaActionPerformed
        int row = tabelaTurmasProfessor.getSelectedRow();
        if (row > -1) {
            tabelaTurmasProfessor.setRowSelectionInterval(row, row);
            Integer id = Integer.valueOf(getTabelaTurmasProfessor().getValueAt(row, 0).toString());
            String nomeIdioma = getTabelaTurmasProfessor().getValueAt(row, 2).toString();
            Integer nivel = Integer.valueOf(getTabelaTurmasProfessor().getValueAt(row, 3).toString());
            AvaliacaoForm af = new AvaliacaoForm();
            af.launch(id, nomeIdioma, nivel, cpf);
        }
    }//GEN-LAST:event_bAvaliarTurmaActionPerformed

    private void bListarMinhasTurmasComEstudantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarMinhasTurmasComEstudantesActionPerformed
        ListaTurmasProfessor ltp = new ListaTurmasProfessor();
        ltp.launch(cpf, Autoridade.PROFESSOR);
    }//GEN-LAST:event_bListarMinhasTurmasComEstudantesActionPerformed

    private void bChangeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChangeUserActionPerformed
        Login l = new Login();
        l.launch();
    }//GEN-LAST:event_bChangeUserActionPerformed

    private void bSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairSistemaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSairSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public void launch() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAvaliarTurma;
    private javax.swing.JButton bChangeUser;
    private javax.swing.JButton bListarMinhasTurmasComEstudantes;
    private javax.swing.JButton bListarTurmas;
    private javax.swing.JButton bSairSistema;
    private javax.swing.JLabel dadosProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaTurmasProfessor;
    // End of variables declaration//GEN-END:variables
    private String nome;
    private String cpf;

    void setDadosProfessor(String nome, String cpf) {
        this.nome = nome;
        this.cpf = cpf;
        dadosProfessor.setText(nome + " (" + cpf + ").");
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCpf() {
        return cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    public void setRowTabelaTurmasProfessor(Object[] data) {
        getTabelaTurmasProfessor().addRow(data);
    }

    public DefaultTableModel getTabelaTurmasProfessor() {
        return (DefaultTableModel) tabelaTurmasProfessor.getModel();
    }
}
