package br.ufsc.ui;

import br.ufsc.control.*;
import java.util.ArrayList;
import java.util.function.Consumer;
import javax.swing.*;

public class ProfessorForm extends javax.swing.JFrame {

    /**
     * Creates new form EstudanteForm
     */
    public ProfessorForm() {
        initComponents();
        initListaIdiomas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfDataNasc = new javax.swing.JTextField();
        tfSenha = new javax.swing.JTextField();
        tfRg = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfCpf = new javax.swing.JTextField();
        bFormSubmeterProfessor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfTel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfEndr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listIdiomasEnsinados = new JList<String>(new DefaultListModel<String>());
        jLabel9 = new javax.swing.JLabel();
        tfIdioma = new javax.swing.JTextField();
        bAdicionarIdiomaProfessor = new javax.swing.JButton();
        bRemoverIdiomaProfessor = new javax.swing.JButton();
        bListarIdiomasProntos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Professor");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Formulário de Cadastro");

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("RG");

        jLabel5.setText("Senha");

        jLabel6.setText("Data de Nascimento");

        tfDataNasc.setText("dd-mm-yyyy");

        bFormSubmeterProfessor.setText("Submeter");
        bFormSubmeterProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFormSubmeterProfessorActionPerformed(evt);
            }
        });

        jLabel7.setText("Telefone");

        jLabel8.setText("Endereço");

        jScrollPane1.setViewportView(listIdiomasEnsinados);

        jLabel9.setText("Línguas Ensinadas");

        tfIdioma.setText("Inglês");

        bAdicionarIdiomaProfessor.setText("Adicionar Língua");
        bAdicionarIdiomaProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdicionarIdiomaProfessorActionPerformed(evt);
            }
        });

        bRemoverIdiomaProfessor.setText("Remover Língua");
        bRemoverIdiomaProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRemoverIdiomaProfessorActionPerformed(evt);
            }
        });

        bListarIdiomasProntos.setText("Lista de Línguas");
        bListarIdiomasProntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarIdiomasProntosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 521, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(bAdicionarIdiomaProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(bRemoverIdiomaProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bListarIdiomasProntos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bFormSubmeterProfessor))
                            .addComponent(tfDataNasc)
                            .addComponent(tfSenha)
                            .addComponent(tfRg)
                            .addComponent(tfCpf)
                            .addComponent(tfNome)
                            .addComponent(tfTel)
                            .addComponent(tfEndr)
                            .addComponent(jScrollPane1)
                            .addComponent(tfIdioma, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEndr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bListarIdiomasProntos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bRemoverIdiomaProfessor))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAdicionarIdiomaProfessor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bFormSubmeterProfessor)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initListaIdiomas() {
        listaIdiomas = new ListaIdiomas();
        DefaultListModel lip = listaIdiomas.getListaIdiomasProntos();
        IdiomaController ic = new IdiomaController();
        ArrayList<String> nomes = ic.getListaNomesDosIdiomas();
        lip.clear();
        for (String nome : nomes) {
            lip.addElement(nome);
        }
    }

    private void bFormSubmeterProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFormSubmeterProfessorActionPerformed
        AuthController ac = new AuthController();
        boolean check = ac.solveNewProfessor(
                tfNome.getText(),
                tfCpf.getText(),
                tfRg.getText(),
                tfSenha.getText(),
                tfDataNasc.getText(),
                tfTel.getText(),
                tfEndr.getText(),
                getComponentListIdiomasEnsinado()
        );

        if (check) {
            dispose();
        } else {
            Mensagem m = new Mensagem();
            m.setMensagemSistema("Verificar se o formulário está preenchido\n"
                    + "Data precisa ser no formato"
                    + "dd-mm-yyyy (i.e. 22-10-1988).\n");
            m.launch();
        }
    }//GEN-LAST:event_bFormSubmeterProfessorActionPerformed

    private void bAdicionarIdiomaProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdicionarIdiomaProfessorActionPerformed
        String aux = tfIdioma.getText().toUpperCase();
        if (!getComponentListIdiomasEnsinado().contains(aux)) {
            getComponentListIdiomasEnsinado().addElement(aux);
        }
    }//GEN-LAST:event_bAdicionarIdiomaProfessorActionPerformed

    private void bRemoverIdiomaProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRemoverIdiomaProfessorActionPerformed
        if (!listIdiomasEnsinados.isSelectionEmpty()) {
            getComponentListIdiomasEnsinado().remove(listIdiomasEnsinados.getSelectedIndex());
        }
    }//GEN-LAST:event_bRemoverIdiomaProfessorActionPerformed

    private void bListarIdiomasProntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarIdiomasProntosActionPerformed
        Consumer<String> consumer = new Consumer<String>() {
            public void accept(String t) {
                tfIdioma.setText(t);
            }
        };

        listaIdiomas.launch(consumer);
    }//GEN-LAST:event_bListarIdiomasProntosActionPerformed

    private DefaultListModel getComponentListIdiomasEnsinado() {
        return (DefaultListModel) listIdiomasEnsinados.getModel();
    }

    /**
     * @param args the command line arguments
     */
    public void launch() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdicionarIdiomaProfessor;
    private javax.swing.JButton bFormSubmeterProfessor;
    private javax.swing.JButton bListarIdiomasProntos;
    private javax.swing.JButton bRemoverIdiomaProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listIdiomasEnsinados;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfDataNasc;
    private javax.swing.JTextField tfEndr;
    private javax.swing.JTextField tfIdioma;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfRg;
    private javax.swing.JTextField tfSenha;
    private javax.swing.JTextField tfTel;
    // End of variables declaration//GEN-END:variables
    private ListaIdiomas listaIdiomas;

    public JTextField getTfCpf() {
        return tfCpf;
    }

    public JTextField getTfEndr() {
        return tfEndr;
    }

    public JTextField getTfNome() {
        return tfNome;
    }

    public JTextField getTfRg() {
        return tfRg;
    }

    public JTextField getTfSenha() {
        return tfSenha;
    }

    public JTextField getTfDataNasc() {
        return tfDataNasc;
    }

    public JTextField getTfTel() {
        return tfTel;
    }

    public ListaIdiomas getListaIdiomas() {
        return listaIdiomas;
    }

    public void setListaIdiomas(ListaIdiomas listaIdiomas) {
        this.listaIdiomas = listaIdiomas;
    }

}
